---
title: "WR_Exploration_3"
author: "Orly Olbum"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(dplyr)
library(tidyr)
library(lubridate)
library(plotly)
```

## Data Prep

```{r data load}
# setwd("/Users/orly/Desktop/Swim Stats/WR Progression")
setwd("/Users/orly/Library/CloudStorage/OneDrive-Personal/Swim Stats/WR Progression")
wr_og = read.csv("WRProgression.csv")
head(wr_og)
```

```{r data setup}
# new columns to split up the distance and the stroke
wr_og = wr_og %>%
  separate("Event", 
           sep = " ", 
           into = c("Distance", "Stroke"), 
           remove = FALSE)
```

```{r setup 2}
# new column to convert it to date format so we can do calculations
wr_og$Date2 = mdy(wr_og$Date)
```

```{r setup 3}
# we are also going to take out "NA" rankings
wr_sub = wr_og %>%
  drop_na(Rank)
```

```{r DaysPassed}
# calculate days between WRs for each event type
wr = wr_sub %>%
  arrange(Event, Date2) %>%
  group_by(Event, Sex) %>%
  mutate(DaysPassed = as.numeric(Date2 - lag(Date2))) %>%
  ungroup()
```


## Fast Ladies
Exploring Mary T Meagher, Tracy Caulkins, and Janet Evans
Define their greatness!
- Count of WRs
- Count of Events
- Time period of WRs (from first date of breaking to breaking of their's by someone else for the last time)

# Mary T

```{r Mary T}
## count of WRs
wr_MaryT = wr %>%
  filter(Name == "Mary T. Meagher")
# print(wr_MaryT)
count_wr_MaryT = nrow(wr_MaryT)
count_wr_MaryT

## count how many different events
events_MaryT = unique(wr_MaryT$Event)
length(events_MaryT)

## how long did she hold any WRs
# first WR
firstwr_MaryT = wr_MaryT[which.min(wr_MaryT$Date2), ]
firstwr_MaryT %>%
  select(Rank, Event, Time, Name, Nationality, Date, Meet, Location)

# last WR
lastwr_MaryT = wr_MaryT[which.max(wr_MaryT$Date2), ]
lastwr_MaryT %>%
  select(Rank, Event, Time, Name, Nationality, Date, Meet, Location)

# last WR broken
# we can see that the last record she set was the 27th ranked 100 fly, so we need the next rank
# let's try to do this without doing it manually

# i tried doing this from the lastwr but that is not necessarily accurate - am i looking for the most recent one, or am i looking for when they no longer held a record?
# the second option is trickier... i think
# let's do this - for all wr's she eld, which one did she hold the longest?

# i'll tackle the other one later
# for lastwr she set, take the date

# filter by event, sex, and rank + 1 from previous dataset - then pull out date
end_MaryT = wr %>%
  filter(
    Event == lastwr_MaryT$Event,
    Sex == lastwr_MaryT$Sex,
    Rank == as.numeric(lastwr_MaryT$Rank) + 1
  )
end_MaryT %>%
  select(Rank, Event, Time, Name, Nationality, Date, Meet, Location)

# take date from that, find days between last date and first date
end_MaryT_date = end_MaryT$Date2
start_MaryT_date = firstwr_MaryT$Date2
MaryT_reign = difftime(end_MaryT_date, start_MaryT_date)
MaryT_reign # auto shows days
time_length(MaryT_reign, unit = "year") # shows years
```


# Tracy C

```{r Tracy C}
## count of WRs
wr_TracyC = wr %>%
  filter(Name == "Tracy Caulkins")
count_wr_TracyC = nrow(wr_TracyC)
count_wr_TracyC

## count how many different events
events_TracyC = unique(wr_TracyC$Event)
events_TracyC
length(events_TracyC)

## how long did she hold any WRs
# first WR
firstwr_TracyC = wr_TracyC[which.min(wr_TracyC$Date2), ]
firstwr_TracyC %>%
  select(Rank, Event, Time, Name, Nationality, Date, Meet, Location)

# last WR
lastwr_TracyC = wr_TracyC[which.max(wr_TracyC$Date2), ]
lastwr_TracyC %>%
  select(Rank, Event, Time, Name, Nationality, Date, Meet, Location)

# last WR broken
# filter by event, sex, and rank + 1 from previous dataset - then pull out date
end_TracyC = wr %>%
  filter(
    Event == lastwr_TracyC$Event,
    Sex == lastwr_TracyC$Sex,
    Rank == as.numeric(lastwr_TracyC$Rank) + 1
  )
end_TracyC %>%
  select(Rank, Event, Time, Name, Nationality, Date, Meet, Location)

# take date from that, find days between last date and first date
end_TracyC_date = end_TracyC$Date2
start_TracyC_date = firstwr_TracyC$Date2
TracyC_reign = difftime(end_TracyC_date, start_TracyC_date)
TracyC_reign # auto shows days
time_length(TracyC_reign, unit = "year") # shows years
```


# Janet E

```{r JanetE}
## count of WRs
wr_JanetE = wr %>%
  filter(Name == "Janet Evans")
count_wr_JanetE = nrow(wr_JanetE)
count_wr_JanetE

## count how many different events
events_JanetE = unique(wr_JanetE$Event)
events_JanetE
length(events_JanetE)

## how long did she hold any WRs
# first WR
firstwr_JanetE = wr_JanetE[which.min(wr_JanetE$Date2), ]
firstwr_JanetE %>%
  select(Rank, Event, Time, Name, Nationality, Date, Meet, Location)

# last WR
lastwr_JanetE = wr_JanetE[which.max(wr_JanetE$Date2), ]
lastwr_JanetE %>%
  select(Rank, Event, Time, Name, Nationality, Date, Meet, Location)

# last WR broken
# filter by event, sex, and rank + 1 from previous dataset - then pull out date
end_JanetE = wr %>%
  filter(
    Event == lastwr_JanetE$Event,
    Sex == lastwr_JanetE$Sex,
    Rank == as.numeric(lastwr_JanetE$Rank) + 1
  )
end_JanetE %>%
  select(Rank, Event, Time, Name, Nationality, Date, Meet, Location)

# take date from that, find days between last date and first date
end_JanetE_date = end_JanetE$Date2
start_JanetE_date = firstwr_JanetE$Date2
JanetE_reign = difftime(end_JanetE_date, start_JanetE_date)
JanetE_reign # auto shows days
time_length(JanetE_reign, unit = "year") # shows years
```

